export enum SponsorshipStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  CLOSED = 'closed',
  DRAFT = 'draft',
  PUBLISHED = 'published',
}

export enum ActionType {
  PUBLISH_SPONSORSHIP_REQUEST = 'PUBLISH_SPONSORSHIP_REQUEST',
  APPROVE_SPONSORSHIP_REQUEST = 'APPROVE_SPONSORSHIP_REQUEST',
  REJECT_SPONSORSHIP_REQUEST = 'REJECT_SPONSORSHIP_REQUEST',
  CLOSE_SPONSORSHIP_REQUEST = 'CLOSE_SPONSORSHIP_REQUEST',
  UPDATE_SPONSORSHIP_REQUEST = 'UPDATE_SPONSORSHIP_REQUEST',
  SUBMIT_SPONSORSHIP_REQUEST = 'SUBMIT_SPONSORSHIP_REQUEST',
  APPROVE_EDIT_REQUEST = 'APPROVE_EDIT_REQUEST',
  REJECT_EDIT_REQUEST = 'REJECT_EDIT_REQUEST',
  APPROVE_PUBLISH_REQUEST = 'APPROVE_PUBLISH_REQUEST',
  REJECT_PUBSLISH_REQUEST = 'REJECT_PUBLISH_REQUEST',
}
export enum PaymentStatus {
  PENDING = 'pending',
  SUCCESS = 'success',
  FAILED = 'failed',
}
